task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path

from tasks.views import (
    index,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerUpdateView,
    PositionListView,
    PositionDetailView,
    PositionDeleteView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskUpdateView,
    WorkerCreateView,
    PositionCreateView,
    TaskTypeCreateView,
    WorkerDeleteView,
    ToggleAssignToTaskView
)


urlpatterns = [
    path("", index, name="index"),
    path("task_list/", TaskListView.as_view(), name="task-list"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "task/<int:pk>/toggle-assign/",
        ToggleAssignToTaskView,
        name="toggle-task-assign",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("worker/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("positions/", PositionListView.as_view(), name="positions-list"),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="positions-detail"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/delete",
        PositionDeleteView.as_view(),
        name="positions-delete",
    ),
    path("task_types/", TaskTypeListView.as_view(), name="task-types"),
    path("task_types/<int:pk>/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("task_types/create", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task_types/<int:pk>/update",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
]

app_name = "tasks"

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
    <div class="container">
      <a class="navbar-brand" href="/" rel="tooltip" data-placement="bottom">
        TaskFlow Manager
      </a>
      <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon mt-2">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </span>
      </button>
      <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
        <ul class="navbar-nav navbar-nav-hover ms-auto">
          <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-5">
            <a href="{% url "tasks:task-list" %}" class="dropdown-item border-radius-md">
                  <span>Tasks</span>
                </a>
          </li>
        </ul>
      </div>
      <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
        <ul class="navbar-nav navbar-nav-hover ms-auto">
          <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-5">
            <a href="{% url "tasks:worker-list" %}" class="dropdown-item border-radius-md">
                  <span>Workers</span>
                </a>
          </li>
        </ul>
      </div>
      <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
        <ul class="navbar-nav navbar-nav-hover ms-auto">
          <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-5">
            <a href="{% url "tasks:positions-list" %}" class="dropdown-item border-radius-md">
                  <span>Positions</span>
                </a>
          </li>
        </ul>
      </div>
      <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
        <ul class="navbar-nav navbar-nav-hover ms-auto">
          <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-5">
            <a href="{% url "tasks:task-types" %}" class="dropdown-item border-radius-md">
                  <span>Task types</span>
                </a>
          </li>
        </ul>
      </div>

          {% if request.user.is_authenticated %}
              <a class="nav-link nav-link-icon me-2"
                href="{% url 'logout' %}">
                <i class="fa fa-sign-out me-1"></i>
                <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</p>
              </a>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} or {{ paginator.num_pages }}</span>
    </li>
  {% if page_obj.has_next %}
    <li class="page-item">
      <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
    </li>
  {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<nav class="navbar" id="mainNav">
  <div class="container">
    <ul class="container navbar-nav flex-row justify-content-center">
      <li class="nav-item mx-3">
        <a class="nav-link active" style="" aria-current="page" href="{% url "tasks:index" %}"><strong>Home</strong></a>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link active" aria-current="page" href="{% url "tasks:task-list" %}">Tasks</a>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link active" aria-current="page" href="{% url "tasks:worker-list" %}">Workers</a>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link active" aria-current="page" href="{% url "tasks:positions-list" %}">Positions</a>
      </li>
      <li class="nav-item mx-3">
        <a class="nav-link active" aria-current="page" href="{% url "tasks:task-types" %}">Task types</a>
      </li>
    </ul>
  </div>
</nav>