task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path

from tasks.views import (
    index,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerUpdateView,
    PositionListView,
    PositionDetailView,
    PositionDeleteView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskUpdateView,
    WorkerCreateView,
    PositionCreateView,
    TaskTypeCreateView,
    WorkerDeleteView,
    ToggleAssignToTaskView
)


urlpatterns = [
    path("", index, name="index"),
    path("task_list/", TaskListView.as_view(), name="task-list"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "task/<int:pk>/toggle-assign/",
        ToggleAssignToTaskView,
        name="toggle-task-assign",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("worker/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("positions/", PositionListView.as_view(), name="positions-list"),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="positions-detail"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/delete",
        PositionDeleteView.as_view(),
        name="positions-delete",
    ),
    path("task_types/", TaskTypeListView.as_view(), name="task-types"),
    path("task_types/<int:pk>/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("task_types/create", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task_types/<int:pk>/update",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
]

app_name = "tasks"

tasks/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Position(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, related_name="workers"
    )

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    deadline = models.DateTimeField(editable=True)
    is_completed = models.BooleanField(default=False)
    PRIORITY_CHOICES = [
        ("low", "Low Priority"),
        ("medium", "Medium Priority"),
        ("high", "High Priority"),
        ("urgent", "Urgent Priority"),
    ]
    priority = models.CharField(choices=PRIORITY_CHOICES, max_length=10)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(Worker, related_name="tasks")

tasks/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404

from tasks.models import Task, Worker, Position


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=Worker.objects.all(), widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "deadline",
            "priority",
            "task_type",
            "is_completed",
            "assignees",
        ]
        widgets = {"deadline": forms.TextInput(attrs={"type": "datetime-local"})}


class PositionForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = ["name"]


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "position",
            "first_name",
            "last_name",
        )


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by position"}),
    )


class WorkerSearchForm(forms.Form):
    last_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by last name"}),
    )


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by task name"}),
    )

tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from tasks.forms import (
    WorkerCreationForm,
    PositionSearchForm,
    WorkerSearchForm,
    TaskSearchForm,
    TaskForm,
    PositionForm,
)
from tasks.models import Worker, Task, Position, TaskType


def index(request):
    num_workers = Worker.objects.count()
    num_tasks = Task.objects.all()
    num_positions = Position.objects.all()

    context = {
        "num_workers": num_workers,
        "num_tasks": num_tasks,
        "num_positions": num_positions,
    }

    return render(request, "tasks/index.html", context=context)


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    template_name = "tasks/task_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TaskSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Task.objects.all()
        form = TaskSearchForm(self.request.GET)

        if form.is_valid():
            name = form.cleaned_data["name"]
            if name:
                queryset = queryset.filter(name__icontains=name)
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")
    template_name = "tasks/task_form.html"


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")
    template_name = "tasks/task_form.html"

    def get(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs["pk"])
        form = TaskForm(instance=task)
        return render(request, "tasks/task_form.html", {"form": form})

    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs["pk"])
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect("task_detail", pk=task.pk)
        
        return self.form_invalid(form)


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:task-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    template_name = "tasks/worker_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)

        last_name = self.request.GET.get("last_name", "")

        context["search_form"] = WorkerSearchForm(initial={"last_name": last_name})
        return context

    def get_queryset(self):
        queryset = Worker.objects.all()
        form = WorkerSearchForm(self.request.GET)

        if form.is_valid():
            last_name = form.cleaned_data["last_name"]
            if last_name:
                queryset = queryset.filter(last_name__icontains=last_name)
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("tasks:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("tasks:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("tasks:worker-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    template_name = "tasks/positions.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = PositionSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)

        if form.is_valid():
            name = form.cleaned_data["name"]
            if name:
                queryset = queryset.filter(name__icontains=name)
        return queryset


class PositionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Position
    template_name = "tasks/position_detail.html"


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy("tasks:positions-list")
    template_name = "tasks/position_form.html"


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("tasks:positions-list")


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    template_name = "tasks/task_type_list.html"
    paginate_by = 5
    ordering = ["name"]


class TaskTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = TaskType
    template_name = "tasks/task_type_detail.html"


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("tasks:task-types")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("tasks:task-types")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("tasks:task-types")


class ToggleAssignToTaskView(generic.View):
    @staticmethod
    def post(request, pk):
        worker = Worker.objects.get(id=request.user.id)
        task = Task.objects.get(id=pk)
        if task in worker.tasks.all():
            worker.tasks.remove(task)
        else:
            worker.tasks.add(task)
        return HttpResponseRedirect(
            reverse_lazy("task_manager:task-detail", args=[pk])
        )

templates/tasks/Index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
  <body id="page-top">
       <header class="masthead" style="padding-top: 10.5rem; padding-bottom: 6rem; text-align: center; color: #fff;
        background-image: linear-gradient(to bottom, rgba(92, 77, 66, 0.5) 0%, rgba(92, 77, 66, 0.5) 100%), url('/static/img/1.jpg');
        background-repeat: no-repeat;
        background-attachment: scroll;
        background-position: center center;
        background-size: cover;">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">Welcome to TaskFlow Manager</h1>
                        <hr class="divider">
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">
                          Introducing our web-based task management platform at our IT company! Experience the
                          convenience of our user-friendly system designed to streamline your task management process.
                          With a range of powerful features, including task assignment, deadline setting, and progress
                          tracking, you can stay organized and enhance your team's efficiency. Embrace our task manager
                          to keep your projects on track and achieve your goals effectively. Join us today and elevate
                          your productivity to new heights!
                        </p>
                        <a class="btn btn-primary btn-xl" href="{% url "login" %}">Get started</a>
                    </div>
                </div>
            </div>
        </header>
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">We've got what you need!</h2>
                        <hr class="divider divider-light">
                        <p class="text-white-75 mb-4">TaskFlow Manager is designed to help you stay organized and productive as you surf through your IT projects. You can effortlessly create, assign, and manage tasks for you and your team. You can easily track progress, set deadlines, and check if tasks are completed, so you can stay on top of your project timeline.</p>
                        <p class="text-white-75 mb-4">Our task manager also allows you to easily search and filter tasks by position, so you can quickly find what you need and get back to work. You can also view task details, including descriptions, comments,all in one place.</p>
                    </div>
                </div>
                </div>
            </div>
        </section>
        <section class="page-section" id="services">
            <div class="container px-4 px-lg-5">
                <h2 class="text-center mt-0">Service</h2>
                <hr class="divider">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">
                              <a class="nav-link active" aria-current="page" href="{% url "tasks:task-list" %}">Tasks</a>
                            </h3>
                            <p class="text-muted mb-0">Efficient task management with user assignments.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-laptop fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">
                              <a class="nav-link active" aria-current="page" href="{% url "tasks:worker-list" %}">Workers</a>
                            </h3>
                            <p class="text-muted mb-0">A comprehensive worker list for easy management and assignment tracking.</p>
                        </div>
                      </div>
                      <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-globe fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">
                              <a class="nav-link active" aria-current="page" href="{% url "tasks:positions-list" %}">Positions</a>
                            </h3>
                            <p class="text-muted mb-0">Seamless integration of position listings with task assignments.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-heart fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">
                              <a class="nav-link active" aria-current="page" href="{% url "tasks:task-types" %}">Task types</a>
                            </h3>
                            <p class="text-muted mb-0">Effortlessly manage tasks with clear task type categorization</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section>
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright © 2023 - TaskFlow Manager</div></div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        </section>
</body>
{% endblock %}

templates/tasks/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="display: flex; align-items: center; margin-top: 200px; justify-content: center; height: 100px; flex-direction: column;">
  <h1>Are you sure to delete this position?</h1>

  <div class="container" style="display: flex; align-items: center; justify-content: center; height: 100px;">
    <h3>{{ position }}</h3>
  </div>

  <div class="container">
    <form action="" method="post" style="float: right; margin-right: 470px">
      {% csrf_token %}

      <br>

      <input type="submit" value="Yes" class="btn btn-danger" style="margin-right: 10px">
      <a class="btn btn-secondary" href="{% url "tasks:positions-list" %}">Cancel</a>
    </form>
  </div>
</div>
{% endblock %}

templates/tasks/position_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
    <div  class="text-white-75 mb-4" style="margin-top: 60px; background-color: #f4623a; color: white; height: 30%">
      <h2 style="text-align: center; margin-left: auto; margin-right: auto">Within this section, you can access a comprehensive list of all workers who have registered for
        and been allocated to this particular position</h2>
    </div>
    <h1 style="text-align: center">{{ object.name }}</h1>
    <table class="table table-striped" style="border: solid; border-color: #f4623a; width: 50%; margin: auto">
      <tr>
      <th style="width: 200px">Username</th>
      <th style="width: 200px">Full name</th>
      </tr>
      {% for worker in object.workers.all %}
        <tr>
        <td>{{ worker.username }}</td>
        <td>{{ worker.first_name }}, {{ worker.last_name }}</td>
      {% endfor %}
      </tr>
    </table>
  </div>
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="display: flex; align-items: center; margin-top: 200px; justify-content: center; height: 100px; flex-direction: column;">
    <h1>Are you sure you want to delete this task?</h1>
    <div class="container" style="display: flex; align-items: center; justify-content: center; height: 100px;">
      <h3> {{ task.name }}</h3>
    </div>
    <div class="container">
      <form action="" method="post" style="float: right; margin-right: 480px">
        {% csrf_token %}

        <br>

        <input type="submit" value="Yes" class="btn btn-danger" style="margin-right: 10px">
        <a class="btn btn-secondary" href="{% url "tasks:task-list" %}">Cancel</a>
      </form>
    </div>
  </div>
{% endblock %}

templates/tasks/task_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
  <br>
  <br>
  <br>
  <div class="container-dt-2">
    <h2>
      {{ task.name }}
    </h2>
  </div>

  <div class="container-dt-3">
    <table class="table table-bordered">
      <td style="width: 200px"><strong>Task type:</strong></td>
      <td>{{ task.task_type.name }}</td>
      <tr></tr>
      <td><strong>Task description:</strong></td>
      <td>{{ task.description }}</td>
      <tr></tr>
      <td><strong>Assignee</strong></td>
        {% if task.assignees.all %}
            <td>
              <ul>
                {% for worker in task.assignees.all %}
                    <li>{{ worker.position }} ({{ worker.first_name }} {{ worker.last_name }})</li>
                {% endfor %}
              </ul>
            </td>
        {% else %}
          <td></td>
        {% endif %}
    </table>
    <br>
    <div>
      <div class="container-dt-1">
        {% if task in user.tasks.all %}
          <a href="{% url 'tasks:toggle-task-assign' pk=task.id %}" class="btn btn-danger link-to-page">
            Delete me from this task
          </a>
        {% else %}
          <a href="{% url 'tasks:toggle-task-assign' pk=task.id %}" class="btn btn-success link-to-page">
            Assign me for this task
          </a>
      {% endif %}
        <a href="{% url 'tasks:task-delete' pk=task.id %}" class="btn btn-danger link-to-page" style="float: right; margin: 10px">
          Delete
        </a>
        <a href="{% url 'tasks:task-update' pk=task.id %}" class="btn btn-secondary link-to-page" style="float: right; margin: 10px">
          Update
        </a>
      </div>
    </div>

  </div>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div>
    <h1 style="text-align: center">{{ object|yesno:"Update,Create" }} Task</h1>

  <form action="" method="post" novalidate class="my-form">
    {% csrf_token %}
    {{ form|crispy}}

    <input type="submit" value="Submit" class="btn btn-primary" style="float: right">
  </form>
  </div>

  <style>
    .my-form {
      width: 50%;
      margin: 0 auto;
    }
  </style>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
   <div>
     <h1 style="text-align: center;">
      Task List
    </h1>
    <form action="" method="GET" class="form-inline" style="margin: 20px">
      {{ search_form|crispy }}
      <input type="submit" value="🔎" class="btn btn-light" style="margin: 10px">
    </form>

    <div style="margin-left: 20px; margin-right: 20px">
      {% if task_list %}
    <div>
      <table class="table table-striped" style="padding: 20px; border: solid; border-color: #f4623a">
      <tr>
        <th style="width: 200px">Name</th>
        <th style="width: 450px">Description</th>
        <th>Dead line date</th>
        <th>Status</th>
        <th>Priority</th>
        <th>Assignees</th>
      </tr>
    {% for task in task_list %}
      <tr>
        <td><a href="{% url "tasks:task-detail" pk=task.id %} ">{{ task.name }}</a></td>
        <td>{{ task.description }}</td>
        <td>{{ task.deadline_date }}</td>
        <td>{{ task.is_completed }}</td>
        <td>{{ task.priority }}</td>
        <td>
          {% for worker in task.assignees.all %}
            {{ worker.username }}
          {% endfor %}
        </td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no tasks in the service.</p>
    {% endif %}
    </div>
    </div>
    <a href="{% url 'tasks:task-create' %}" class="btn btn-primary link-to-page" style="float: right; margin-right: 30px">
        Create
    </a>
   </div>
{% endblock %}

templates/tasks/task_type_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
  <br>
  <br>
  <br>
  <div class="container-dt-2">
    <h2>
      {{ object.name }}
    </h2>
  </div>
  <div class="container-dt-3">
  {% for task in object.task_set.all %}
    <table class="table table-bordered">
      <td style="width: 200px"><strong>Task name:</strong></td>
        <td>{{ task.name }}</td>
      <tr></tr>
      <td><strong>Task description:</strong></td>
        <td>{{ task.description }}</td>
      <tr></tr>
          <hr style="color: #f4623a;">

    </table>
    {% endfor %}
    <br>
    <div>
{% endblock %}

templates/tasks/task_type_list.html
{% extends "base.html" %}

{% block content %}
  <div  class="text-white-75 mb-4" style="margin-top: 60px; background-color: #f4623a; color: white; height: 30%px">
    <h2 style="text-align: center; margin-left: 300px; margin-right: 300px">We hope this page helps you navigate our tasks more easily and find the information you need by task type</h2>
  </div>
<div>
  <h1 style="text-align: center">
    Task types
  </h1>
  <br>
</div>
<div style="margin-left: 20px; margin-right: 20px">
  {% if tasktype_list %}
    <table class="table table-striped" style="border: solid; border-color: #f4623a; width: 50%; margin: auto">
      <tr>
        <th style="text-align: center; width: 100px">ID</th>
        <th style="text-align: center; width: 100px">Type</th>
      </tr>
      {% for tasktype in tasktype_list %}
        <tr>
          <td style="text-align: center">{{ tasktype.id }}</td>
          <td style="text-align: center"><a href="{% url "tasks:task-type-detail" pk=tasktype.id %}">{{ tasktype.name }}</a></td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}
</div>
{% endblock %}

templates/tasks/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container" style="display: flex; align-items: center; margin-top: 200px; justify-content: center; height: 100px; flex-direction: column;">
    <h1>Are you sure you want to delete this worker?</h1>
    <div class="container" style="display: flex; align-items: center; justify-content: center; height: 100px;">
      <h3> {{ worker.username }}, {{ worker.position }}</h3>
    </div>
    <div class="container">
      <form action="" method="post" style="float: right; margin-right: 480px">
        {% csrf_token %}

        <br>

        <input type="submit" value="Yes" class="btn btn-danger" style="margin-right: 10px">
        <a class="btn btn-secondary" href="{% url "tasks:worker-list" %}">Cancel</a>
      </form>
    </div>
  </div>
{% endblock %}

templates/tasks/worker_detail.html
{% extends "base.html" %}

{% block content %}
  <div>
  <br>
  <br>
  <br>
  <div class="container-dt-2">
    <h2>
      {{ object.name }}
    </h2>
  </div>
  <div class="container-dt-3">
  {% for worker in object.task_set.all %}
    <table class="table table-bordered">
      <td style="width: 200px"><strong>Worker full name:</strong></td>
        <td>{{ worker.first_name }} {{ worker.last_name }}</td>
      <td style="width: 200px"><strong>Worker position:</strong></td>
        <td>{{ worker.position }}</td>
      <tr></tr>
      <td><strong>Task description:</strong></td>
        <td>{{ task.description }}</td>
      <tr></tr>
          <hr style="color: #f4623a;">

    </table>
    {% endfor %}
    <br>
    <div>
{% endblock %}

templates/tasks/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div>
    <h1 style="text-align: center">{{ object|yesno:"Update,Create" }} Worker</h1>
    <form action="" method="post" novalidate class="my-form">
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
  </div>

  <style>
    .my-form {
      width: 50%;
      margin: 0 auto;
    }
  </style>
{% endblock %}

templates/tasks/worker_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div>
    <h1 style="text-align: center">
      Worker List
    </h1>
    <form action="" method="GET" class="form-inline" style="margin: 20px">
      {{ search_form|crispy }}
      <input type="submit" value="🔎" class="btn btn-light" style="margin: 10px">
    </form>
    <div style="margin-left: 20px; margin-right: 20px">
      {% if worker_list %}
        <table class="table table-striped" style="padding: 20px; border: solid; border-color: #f4623a">
          <tr>
            <th style="text-align: center">ID</th>
            <th>Position</th>
            <th>Username</th>
            <th>Full name</th>
            {% if user.is_superuser %}
              <th>Update</th>
              <th>Delete</th>
            {% endif %}
          </tr>
        {% for worker in worker_list %}
          <tr>
            <td style="text-align: center">{{ worker.id }}</td>
            {% if worker.position %}
              <td><a href="{% url "tasks:positions-detail" pk=worker.position.pk %}">{{ worker.position }} {% if user == worker %} (Me){% endif %}</a></td>
            {% else %}
              <td></td>
            {% endif %}
            <td>{{ worker.username }}</td>
            <td>{{ worker.first_name }} {{ worker.last_name }}</td>
            {% if user.is_superuser %}
              <td><a href="{% url "tasks:worker-update" pk=worker.id %}" style="color: #1b1b1b">Update</a></td>
              <td><a href="{% url "tasks:worker-delete" pk=worker.id %}" style="color: #1b1b1b">Delete</a></td>
            {% endif %}
          </tr>
        {% endfor %}

        </table>
        {% else %}
          <p>There are no workers in the service.</p>
        {% endif %}
    </div>
    <div>
      <h1>
        <a href="{% url 'tasks:worker-create' %}" class="btn btn-primary link-to-page" style="float: right; margin: 30px">
          Create
        </a>
        </h1>
    </div>
  </div>
{% endblock %}